### ISSUE TITLE
Authorization token

### ISSUE THREAD

**Issue by axzxc1236** [muhammadh-s/order-pizza-rest-api#3]
(1) The website didn't tell us how to use authorization token. (Spoiler: add the following request header "authorization: Bearer \<JWT\>")

(2) When I am poking at authorization header, it returned the following error message

> {"msg":"Bad Authorization header. Expected value 'Bearer \<JWT\>'"}

It just spits out the token needed to add an order, this is definitely a bug right?

(3) How am I suppose to do with the token generated by "/auth"? Looks like the token is useless.

**Comment by mhshahzad** [comment]
1. The website is a swagger template generated. Though, It is a norm to use JWT as you stated.
2. You should go through the source files. The response is handled by the flask-jwt-extended package.
3. I think you did not go through the repository. The README.md file states that the token should be used while generating an order. 

However, for clarity, I can update the README file.
