### ISSUE TITLE
Not enough segment when adding order

### ISSUE THREAD

**Issue by axzxc1236** [muhammadh-s/order-pizza-rest-api#4]
> curl -X POST --header 'Content-Type: application/json' --header 'authorization: Bearer \<JWT\>' --header 'Accept: application/json' -d '{"Crust":"a", "Flavor":"b", "Size":"Big", "Table_No":3}' 'https://order-pizza-api.herokuapp.com/api/orders'

I tried the above command to add order to your web app, it keeps returning

> {"msg":"Not enough segments"}

I have no clue what this error is about.

**Comment by mhshahzad** [comment]
The error originates from the Authorization module. In your cURL request, `<JWT>` must be replaced with the token. Now I think you know why the token is not useless.
